FROM flink:2.1.1

ARG FLINK_VERSION=2.1.1
ARG KAFKA_CONNECTOR_VERSION=4.0.1-2.0

ENV PYTHONPATH=/opt/flink/opt/python/pyflink:/opt/flink/opt/python
ENV PYFLINK_CLIENT_EXECUTABLE=/usr/bin/python3

RUN mkdir -p /opt/flink/lib

RUN set -e \
    && apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-pip python3-distutils curl ca-certificates unzip \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && curl -L -o /opt/flink/lib/flink-sql-connector-kafka-${KAFKA_CONNECTOR_VERSION}.jar \
    https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/${KAFKA_CONNECTOR_VERSION}/flink-sql-connector-kafka-${KAFKA_CONNECTOR_VERSION}.jar \
    && pip3 install --no-cache-dir typing_extensions protobuf apache-flink==${FLINK_VERSION} \
    && mkdir -p /opt/flink/opt/python/pyflink \
    && unzip -q /opt/flink/opt/python/pyflink.zip -d /opt/flink/opt/python/pyflink \
    && chmod +x /opt/flink/opt/python/pyflink/pyflink/bin/pyflink-udf-runner.sh \
    && rm -rf /var/lib/apt/lists/*
